DescribeForm/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace DescribeForm.Models
{
    public class ApplicationDbContext :DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) 
        { 
        }
    public DbSet<Describe> Describes {  get; set; }
    }
}

DescribeForm/Models/Command/DeleteDescribeCommand .cs
using System.ComponentModel.DataAnnotations;

namespace DescribeForm.Models.Command
{
    public class DeleteDescribeCommand
    {
        public int Id { get; set; }

    }
}

DescribeForm/Models/Command/EditDescribeCommand.cs
using System.ComponentModel.DataAnnotations;

namespace DescribeForm.Models.Command
{
    public class EditDescribeCommand
    {
        public int Id { get; set; }

        [Display(Name = "ثبت شرح جدید")]
        [MaxLength(50, ErrorMessage = "این فیلد نباید بیشتر از 250 کاراکتر باشد!")]
        [Required(ErrorMessage = "این فیلد نباید خالی باشد! ")]
        public string Name { get; set; }
    }
}

DescribeForm/Models/Command/RegisterDescribeCommand.cs
using System.ComponentModel.DataAnnotations;

namespace DescribeForm.Models.Command
{
    public class RegisterDescribeCommand
    {
        [Display(Name = "ثبت شرح جدید ")]
        [MaxLength(250, ErrorMessage =  "این فیلد نباید بیشتر از 250 کاراکتر باشد!")]
        [Required (ErrorMessage = "این فیلد نباید خالی باشد! ")]
        public string Name { get; set; }

    }
}

DescribeForm/Models/Describe.cs
namespace DescribeForm.Models
{
    public class Describe
    {
        public int Id { get; set; }

        public string? Name {  get; set; }
    }
}

DescribeForm/Controllers/DescribeController.cs
using DescribeForm.Models;
using DescribeForm.Models.Command;
using DescribeForm.Services.Implementation;
using DescribeForm.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace DescribeForm.Controllers
{
    public class DescribeController : Controller
    {
        private readonly ICommandDescribeService commandDescribeService;
        private readonly IDescribesService describesService;

        public DescribeController(ICommandDescribeService commandDescribeService, IDescribesService describesService)
        {
            this.commandDescribeService = commandDescribeService;
            this.describesService = describesService;
        }
        public IActionResult Index()
        {
            var describes = describesService.GetAllDescribes();
            return View(describes);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("_Create");
        }
        [HttpPost]
        public async Task<IActionResult> Create(RegisterDescribeCommand command)
        {
            var id = commandDescribeService.RegisterDescribe(command);
            var describes = describesService.GetAllDescribes();
            return PartialView("_TableBody", describes);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var describe = describesService.GetDescribe(id);

            var command = new EditDescribeCommand()
            {
                Id = describe.Id,
                Name = describe.Name,
            };

            return PartialView("_Edit", command);
        }

        [HttpPost]
        public IActionResult Edit(EditDescribeCommand command)
        {
            commandDescribeService.EditDescribe(command);
            var describes = describesService.GetAllDescribes();
            return PartialView("_TableBody", describes);
        }

        [HttpPost]
        public void Delete(int id)
        {
            commandDescribeService.DeleteDescribe(id);
        }
    }
}

DescribeForm/Controllers/HomeController.cs
using DescribeForm.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DescribeForm.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext db;

        public HomeController(ApplicationDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            //var describe = new Describe()
            //{
            //    Name = "test",
            //};
            //db.Describes.Add(describe);
            //db.SaveChanges();
            return View();
        }
    }
}

DescribeForm/Views/Describe/Index.cshtml
@model IEnumerable<DescribeForm.Models.Describe>

@{
    ViewData["Title"] = "Index";
}



<p>
    <a href="#" onclick="addDescribe()">
        <h1>فرم تعریف شرح ثابت</h1>
    </a>
</p>

<style>
    .fa.button {
        padding-right: 5px;
        padding-left: 5px;
    }

        .fa.button:hover {
            opacity: 0.7;
            cursor: pointer;
        }
</style>

<table class="table" id="table-describes">
    <thead>
        <tr>
          @*   <th>
                @Html.DisplayNameFor(model => model.)
            </th>
            <th></th> *@
        </tr>
    </thead>
    <tbody>
        @(await Html.PartialAsync("_tableBody", Model))
    </tbody>
</table>

@section Scripts{
    <script>

        //$('[data-toggle="tooltip"]').tooltip();

        function addDescribe() {

            var dialog = bootbox.confirm(
                {
                    size: 'xl',
                    title: "شرح ",
                    message: "Loading ...",
                    buttons: {
                        confirm: {
                            label: "Submit",
                            className: "btn-success"
                        },
                        cancel: {
                            label: "Cancel",
                            className: "btn-danger"
                        }
                    },
                    callback: function (result) {
                        if (result === true) {

                            $("#create-form").removeData("unobtrusiveValidation");
                            $.validator.unobtrusive.parse($("#create-form"));
                            if (! $("#create-form").valid()){
                                $("#create-form").validate();
                                return false;
                            }

                            var formData = $("#create-form").serializeArray();
                            $.ajax({
                                url: "/Describe/Create",
                                method: "Post",
                                data: formData,
                                success: function (data) {
                                    dialog.modal("hide");

                                    $('tbody').html(data);

                                },
                                error: function (result) {

                                }
                            });


                            return false;
                        }
                    }
                }
            );
            dialog.init(function () {

                $.ajax({
                    url: "/Describe/Create",
                    method: "Get",
                    success: function (data) {
                        dialog.find(".bootbox-body").html(data);
                    },
                    error: function (result) {

                    }
                });

            });
        }


        function edit(id) {

            var dialog = bootbox.confirm(
                {
                    size: 'xl',
                    title: "Add Describe",
                    message: "Loading ...",
                    buttons: {
                        confirm: {
                            label: "Submit",
                            className: "btn-success"
                        },
                        cancel: {
                            label: "Cancel",
                            className: "btn-danger"
                        }
                    },
                    callback: function (result) {
                        if (result === true) {

                            $("#edit-form").removeData("unobtrusiveValidation");
                            $.validator.unobtrusive.parse($("#edit-form"));
                            if (!$("#edit-form").valid()) {
                                $("#edit-form").validate();
                                return false;
                            }

                            var formData = $("#edit-form").serializeArray();
                            $.ajax({
                                url: "/Describe/Edit",
                                method: "Post",
                                data: formData,
                                success: function (data) {
                                    dialog.modal("hide");

                                    $('tbody').html(data);

                                },
                                error: function (result) {

                                }
                            });


                            return false;
                        }
                    }
                }
            );
            dialog.init(function () {

                $.ajax({
                    url: "/Describe/Edit/" + id,
                    method: "Get",
                    success: function (data) {
                        dialog.find(".bootbox-body").html(data);
                    },
                    error: function (result) {

                    }
                });

            });
        }


        function deleteDescribe(id , Name, e) {

            bootbox.confirm(
                {
                    size: 'small',
                    buttons: {
                        confirm: {
                            label: "Yes",
                            className: "btn-success"
                        },
                        cancel: {
                            label: "No",
                            className: "btn-danger"
                        }
                    },
                    message: 'آیا از حذف این اطلاعات مطمین هستید؟' + Name + ' ' + '?',
                    callback: function (result) {
                        if (result === true) {

                            $.ajax({
                                url: "/Describe/Delete/" + id,
                                method: "Post",
                                success: function (result) {
                                    //window.location.reload();
                                    $(e.target).closest('tr').remove();
                                },
                                error: function (result) {
                                    debugger;
                                }
                            });
                        }

                    }
                }
            );
        }


    </script>
}

DescribeForm/Views/Describe/_Create.cshtml
@using DescribeForm.Models.Command
@model RegisterDescribeCommand
@{
    Layout = null;
}

<form method="post" id="create-form">

    <div class="row g-3">
        <div class="col-sm">
            @Html.TextBoxFor(x=> x.Name, "", new{@class ="form-control", @placeholder=Html.DisplayNameFor(x=>x.Name)})
            @Html.ValidationMessageFor(x=>x.Name, "", new{@class="text-danger"})
        </div>
    </div>
    <div>

    @* </div>
    <<div class="row g-3">
        <div class="col-sm">
            <button type="submit" class="btn btn-success">Submit</button>
            <a class="btn btn-secondary" href="describe/index">Cancel</a>
        </div>
    </div> *@
</form>

@section Scripts {
    @*@{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

DescribeForm/Views/Describe/_Delete.cshtml
@using DescribeForm.Models.Command
@model DeleteDescribeCommand

@{
    Layout = null;
}

<div>
    <form>
        <div class="row g-3">
            <div class="col-sm">
                @Html.TextBoxFor(x => x.Id, "Describe Id You Want to Delete",new{@class ="form-control" , @placeholder=Html.DisplayNameFor(x=>x.Id)})
                @Html.ValidationMessageFor(x => x.Id, "", new{@class="text-danger" ,@readonly=true})
                </div>
            </div>
    </form>

        <form method="post" >
            @Html.HiddenFor(x=>x.Id)
        <div class="row g-3">
            <div class="col-sm">
                <button type="submit" class="btn btn-success">Delete</button>
                <a class="btn btn-secondary" href="describe/index">Cancel</a>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @*@{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @*<script>
        $('.datepicker').datepicker();
    </script>*@
}

DescribeForm/Views/Describe/_Edit.cshtml
@using DescribeForm.Models.Command
@model EditDescribeCommand
@{
    Layout = null;
}
<form method="post" id="edit-form">


    @Html.HiddenFor(x=>x.Id)
    <div class="row g-3">
        <div class="col-sm">
            @Html.TextBoxFor(x=> x.Name, "", new{@class ="form-control", @placeholder=Html.DisplayNameFor(x=>x.Name)})
            @Html.ValidationMessageFor(x=>x.Name, "", new{@class="text-danger"})
        </div>
    </div>
    <div>

    </div>

  @*   <<div class="row g-3">
        <div class="col-sm">
            <button type="submit" class="btn btn-success">Submit</button>
            <a class="btn btn-secondary" href="describe/index">Cancel</a>
        </div>
    </div> *@
</form>

@section Scripts {
    @*@{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

  
}

DescribeForm/Views/Describe/_TableBody.cshtml
@model IEnumerable<DescribeForm.Models.Describe>


    

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        
        <td>
            <i class="fa fa-pencil button" data-toggle="tooltip"  title="Edit" style="color:blue;" onclick="edit(@item.Id)"></i>
            <i class="fa fa-trash-o button" data-toggle="tooltip" title="Delete" style="color:red;" onclick="deleteDescribe(@item.Id, '@item.Name', event)"></i>
        </td>
    </tr>
}

DescribeForm/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DescribeForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DescribeForm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/jquery.ui/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DescribeForm.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DescribeForm</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Describe" asp-action="Index">Describes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DescribeForm - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/6.0.0/bootbox.min.js" integrity="sha512-oVbWSv2O4y1UzvExJMHaHcaib4wsBMS5tEP3/YkMP6GmkwRJAa79Jwsv+Y/w7w2Vb/98/Xhvck10LyJweB8Jsw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>